### ISSUE TITLE
Issues in compilation when used with python related dependencies

### ISSUE THREAD

**Issue by skarred14** [Microsoft/Docker.DotNet#101]
Using v2.124.1, I was trying to add references to IronPython, Microsoft.Scripting, and Microsoft.Dynamic. Upon building and compiling the application, I get the following error:

Server Error in '/' Application.

Compilation Error 
  Description: An error occurred during the compilation of a resource required to service this request. Please review the following specific error details and modify your source code appropriately. 

 Compiler Error Message: CS0121: The call is ambiguous between the following methods or properties: 'System.TypeExtensions.GetTypeInfo(System.Type)' and 'System.Reflection.IntrospectionExtensions.GetTypeInfo(System.Type)'

Source Error:
Line 11:         public bool CanConvert(Type t)
Line 12:         {
Line 13:             return typeof (IList).GetTypeInfo().IsAssignableFrom(t.GetTypeInfo()) || typeof (IDictionary).GetTypeInfo().IsAssignableFrom(t.GetTypeInfo());
Line 14:         }
Line 15: 
  
If i remove the references to the above dll's the compilation works fine. Any advice as to how to get around this issue?

**Comment by jterry75** [comment]
What TFM (Target Framework Moniker) are you compiling your app for? Can I see its project.json?

**Comment by jterry75** [comment]
@skarred14 - Please reopen if you still need this investigated.
