### ISSUE TITLE
Docker Remote API access is not enabled on Docker for Windows

### ISSUE THREAD

**Issue by selaskar** [Microsoft/Docker.DotNet#109]
```
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```

**What version of Docker.DotNet?:**

```
2.124.1
```

**Steps to reproduce the issue:**
1. We create a docker client with our presumed client configuration.
2. Any attempt to access to remote api (list containers, start/stop container) fails with "Connection failed" error. 

**What actually happened?:**
We suspect that remote api of Docker is not accessible. We use Docker for Windows and couldn't find any tutorial about how to enable access to it. Your help will be appreciated.

**Comment by jterry75** [comment]
Is the Docker service remote or local?

* If it is local you will be connecting by named pipes by default.
* If it is remote you will need to tell the Windows Docker Daemon to actually bind to a tcp port on startup so that you can make the remote connection.

**Comment by selaskar** [comment]
We are running it under Hyper-V. We want to use Remote API to start/stop containers etc. We are able to do it, when we use Virtual Box. Because when we select Virtual Box, Docker uses different linux os. And we are able to connect to it via ssh. But the one it uses with Hyper-V, doesn't allow us to connect in any way. If you suggest that we need to use named pipes, can you lead us to some resource to study on?

**Comment by jterry75** [comment]
I'm not sure I totally follow yet. A few things are going on here. By default I assume you are trying to use tcp:// on the `DockerClient` connection but by default Docker on Windows uses pipes. You need to start the Docker daemon with -H tcp://<ip>:<port> so that you can then connect to it using tcp in the client. This should work locally or remotely and bridge any connection gap you are talking about in your configuration.

**Comment by stefanprodan** [comment]
Docker for Windows uses a named pipe `npipe:////./pipe/docker_engine` to access the REST API. You have to map the pipe to a tcp port.

This can be done with [socat](http://www.heise.de/download/product/socat-80978/download):

```
socat TCP-LISTEN:2375,reuseaddr,fork PIPE:\\.\pipes\docker_engine
```

After running socat map, you can connect using `tcp://localhost:2375`

More info on this issue [here](https://youtrack.jetbrains.com/issue/WI-32733#u=1470082504230).

**Comment by selaskar** [comment]
Thanks for your helpings.

**Comment by bsnuggs1** [comment]
If anyone needs an alternative solution to this, I used [google's tcpproxy](https://github.com/google/tcpproxy) to make a quick Go app to redirect traffic from the :2375 tcp port to the :2375 loopback.  It's only a few lines of code:

`
package main

import (
	"log"

	"github.com/google/tcpproxy"
)

func main() {
	var p tcpproxy.Proxy
	p.AddRoute(":2375", tcpproxy.To("0.0.0.0:2375"))
	log.Fatal(p.Run())
}
`

**Comment by arnauldvm** [comment]
> Docker for Windows uses a named pipe `npipe:////./pipe/docker_engine` to access the REST API. You have to map the pipe to a tcp port.
> 
> This can be done with [socat](http://www.heise.de/download/product/socat-80978/download):
> 
> ```
> socat TCP-LISTEN:2375,reuseaddr,fork PIPE:\\.\pipes\docker_engine
> ```
> 
> After running socat map, you can connect using `tcp://localhost:2375`

You saved my day!
