### ISSUE TITLE
Installation of Docker.DotNet fails with: "Failed to add reference to 'System.Runtime'. Please make sure that it is in the Global Assembly Cache"

### ISSUE THREAD

**Issue by christianhuening** [Microsoft/Docker.DotNet#111]
Tried to install Docker.DotNet 2.124.1 on Windows 10 in Visual Studio 15 Update 3, but that failed with "Failed to add reference to 'System.Runtime'. Please make sure that it is in the Global Assembly Cache".

**What version of Docker.DotNet?:**

```
2.124.1
```

**Steps to reproduce the issue:**
1. Install Docker.DotNet 2.124.1 via Nuget on Windows 10 in a project targeting .NET 4.6

**What actually happened?:**
Installation of Docker.DotNet fails with "Failed to add reference to 'System.Runtime'. Please make sure that it is in the Global Assembly Cache"

**What did you expect to happen?:**
Package should install smoothly

**Additional information:**
According to this post: https://github.com/aspnet/Home/issues/1157 , it can be fixed by adding System.Net.Runtime as build-type dependency.

**Comment by jterry75** [comment]
@christianhuening - This was fixed in #105 but we have not published an update to Nuget.org yet. Would you be willing to build this updated package and tell me if it fixes your problem?

**Comment by christianhuening** [comment]
@jterry75 Greatly appreciated! I already tried to build the master branch yesterday but got a build error on the .NET 4.6 target. Do you mean to try the head of master or the exact commit state for #105 ? (https://github.com/Microsoft/Docker.DotNet/commit/1ac474c56515197b957e17794eb1e179ede27b45)

**Comment by christianhuening** [comment]
@jterry75 Hm I am seeing errors on our Linux build server. Will need to investigate further.

**Comment by christianhuening** [comment]
@jterry75 #105 fixes the issue for me. 2.124.2 works fine so far.
Thanks!

**Comment by andrewhart098** [comment]
Ran into this error as well.  It would be nice to see an update of this project on Nuget.org.

**Comment by christianhuening** [comment]
Agreed this should be on nuget.org. We're living off of a private nuget repository which acts as a cash and serves internal packages to us. So I almost forgot about it.
@jterry75 can you do that?
