### ISSUE TITLE
GetSystemInfoAsync NetIPNet deserialization error

### ISSUE THREAD

**Issue by stefanprodan** [Microsoft/Docker.DotNet#116]
Hello,

Running `GetSystemInfoAsync ` on a fresh docker install  (version: 1.12.1, API version:  1.24) crashes with the following error:

```
Error converting value "127.0.0.0/8" to type 'Docker.DotNet.Models.NetIPNet'. Path 'RegistryConfig.InsecureRegistryCIDRs[0]', line 1, position 1046.
```

I'm using the latest Docker.DotNet code 6a3fa67ec576c6d64c5a78ab3a7b78aeb9e0e908

**Comment by stefanprodan** [comment]
I think the InsecureRegistryCIDRs should be changed to string array since Json can't deserializate a string to NetIPNet.

```
public IList<string> InsecureRegistryCIDRs { get; set; }
```

**Comment by jterry75** [comment]
@stefanprodan - Want to look at the pull request? This should solve your issues. Thanks for finding it!

**Comment by stefanprodan** [comment]
Yes that solves it. Thanks
