### ISSUE TITLE
Using ListContainersAsync with Filters

### ISSUE THREAD

**Issue by cassiobsilva** [Microsoft/Docker.DotNet#121]
Hi everyone, I'm trying to figure out how to use the ListContainersAsync's **Filters**, but I always get the same result, as if no filter is being used at all.
I can list only the containers with state *created* making a request to ``/containers/json?all=1&filters={"status":["created"]}``, so I don't think it's an issue with the Docker API.

I tried filtering by Label and Status, like the example below:
```
client.Containers.ListContainersAsync(new ContainersListParameters
{
   All = true,
   Filters = new Dictionary<string, Dictionary<string, bool>>
       {
           {
               "status", new Dictionary<string, bool>
                   {
                       { "created", true }
                   }
           }
       } as IDictionary<string, IDictionary<string, bool>>
})
```
PS: I don't really know what the boolean parameter in the second Dictionary does, so I've just used ``true``.

**My environment information:**

**Docker.DotNet version**: 2.124.1

**.NET**:
```
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```
**Docker**:
```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:
 OS/Arch:      linux/amd64
```

**Comment by jterry75** [comment]
@cassiobsilva - I wholeheartedly agree this is a very odd way to do things. Unfortunately however, this is what Docker has chosen for their API. Your doing everything right here for example: [Docker-PowerShell](https://github.com/Microsoft/Docker-PowerShell/blob/master/src/Docker.PowerShell/Objects/ContainerOperations.cs#L83) you can see your doing the same thing we did there.

A quick note however, not all keys are queryable. Try using "id" like our example to see if your code is working. Then go back to "status" and "created". You could also try this from the docker cli. I can't remember the exact syntax but its something like `docker ps -a --filter "status=created"`

**Comment by cassiobsilva** [comment]
Hi @jterry75, thanks for answering.

I found out that using ``as IDictionary<string, IDictionary<string, bool>>`` was causing the issue.
After changing from ``new Dictionary<string, Dictionary<string, bool>>`` to ``new Dictionary<string, IDictionary<string, bool>>`` the filter works perfectly.

Thanks, sorry for the inconvenience.

**Comment by jterry75** [comment]
No inconvenience. Glad its working!
