### ISSUE TITLE
Allow specifying "logs" parameter to the Container Attach operation

### ISSUE THREAD

**Issue by enyim** [Microsoft/Docker.DotNet#128]
**Output of `dotnet --info`:**

```
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
```

**What version of Docker.DotNet?:**

```
2.124.1
```

**Steps to reproduce the issue:**
ContainerAttachParameters does not have a Logs property

**Additional information:**

This in relation of PR #127. 

I may be wrong but I did not find any mention of the Logs parameter in the engine-api sources, no matter which commit I checked. (https://github.com/docker/engine-api/blob/master/types/client.go)

What should be the proper course of action here? Update the generated file manually? Send a PR first to docker, then regen the client after it's accepted?

A faster option would be probably making QueryStringParameter (and related classes) public, so users could inherit from the Models and use their own when needed. 

This way we could use experimental/beta/newer API versions, with an older client (until it gets officially updated).

**Comment by jterry75** [comment]
Ah interesting. This stamp was actually done on the v1.24-rc4 release of Docker as the release indicates. Now that the v1.24 release has been fully stamped I can update the vendor and regen they types. I will submit a PR for this today. Thanks!

**Comment by jterry75** [comment]
This was incorrectly closed.
