### ISSUE TITLE
Passing parameters to start container

### ISSUE THREAD

**Issue by JosephWoodward** [Microsoft/Docker.DotNet#136]
Hi, I'm currently using Docker.DotNet in a project and need to pass parameters when starting a container. 

Having looked at the source code I see StartContainerAsync takes `ContainerStartParameters ` which only has a `DetachKeys` property which is a string. Is this what is used to pass parameters to the starting container or is there another method of doing it? If so, is there an example of how it's formatted?

Thanks!

**Comment by jterry75** [comment]
What "parameters" are you trying to pass? It is likely that you wanted to pass them at create instead of start

**Comment by anujkumaraurea** [comment]
Its actually a valid scenario. I need to pass parameters to my docker container and the parameters are dynamic in nature, they just cant be "hard-coded" in dockerfile.

**Comment by anujkumaraurea** [comment]
Actually on second thought, I think Justin is right. I got confused CreateContainer with Image.

**Comment by JosephWoodward** [comment]
Hi @jterry75,

I'm new to the Docker Remote API, but when running an image you pass in arguments, for instance:

`docker run -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=yourStrong(!)Password' -p 1433:1433 -d microsoft/mssql-server-linux`

I suppose I was expecting to see this on the `StartContainerAsync` method (likening start to Docker's `run` command, but having seen your response and looking at the `CreateContainerAsync` I was clearly looking in the wrong place and don't understand how the Remote API works.

**Comment by jterry75** [comment]
@JosephWoodward - Yea, unfortunately the docker remote API and the docker CLI are quite different in some cases. In the case of `docker run` there is a `create/attach/start` sequence that happens. Glad that `create/start` workflow does what you need. If you find anything missing please let me know and I will update the models.
