### ISSUE TITLE
Using npipe://localhost/... vs npipe://./... for the connection fails.

### ISSUE THREAD

**Issue by HarshaShah** [Microsoft/Docker.DotNet#145]
**What version of Docker.DotNet?:**

Latest.

**Steps to reproduce the issue:**
1. DockerClientConfiguration with URI - npipe://localhost/pipe/docker_engine
2. Call CreateClient 
3. Call ListImagesAsync, it throws following exception 

System.UnauthorizedAccessException: Access to the path is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Pipes.NamedPipeClientStream.Connect(Int32 timeout)
   at System.Threading.Tasks.Task.Execute()

I am running my application as "Administrator", I also tried to specify groups in dockers defualt configuration file. Made sure that named pipe docker_engine has RW permissions to required groups and my application is run as appropriate user still I am continuously getting above exception.

**Additional information:**

Windows 2016 Standard
Docker version 
 Version:      1.12.2-cs2-ws-beta
 API version:  1.25

I am calling this API from my C++/CLI code

Please help me.

**Comment by jterry75** [comment]
I'm not 100% sure this is the issue but can you try something for me? In our project we use `npipe://./pipe/docker_engine` rather than `.../localhost/...`. If this is indeed the issue I can make a fix to convert `localhost` to `.` before calling.

**Comment by HarshaShah** [comment]
Thanks Justin for the reply.

As you suggested I tried with . instead of localhost and it worked.

thanks a lot!

-Harsha

**Comment by jterry75** [comment]
Awesome thanks for the confirmation. I have marked this a bug and we will try to normalize anyone who types "localhost" to be . to avoid this issue in the future!
