### ISSUE TITLE
Implement the Swarm Tasks API surface.

### ISSUE THREAD

**Issue by jterry75** [Microsoft/Docker.DotNet#158]
On the `ISwarmOperations` interface we need to add the `/tasks/*` API surface.

**Comment by galvesribeiro** [comment]
@jterry75 I saw someone implemented Swarm operations... Can we have at least a pre-release nuget? I'm doing some work for MSR/Orleans teams internally and I need to use Swarm.

Thanks

**Comment by swernli** [comment]
Sorry for the lack of response... Justin is out of office for a while, so we will be able to circle back on this once he gets back.

**Comment by galvesribeiro** [comment]
Hey @swernli thanks for get back. Will ping you internally.

**Comment by jterry75** [comment]
Working on this. Will submit for PR today.
