### ISSUE TITLE
IImageOperations should contain the image portion of MiscOperations

### ISSUE THREAD

**Issue by jterry75** [Microsoft/Docker.DotNet#161]
In order to better accommodate the public docker api docs grouping our API function with how docker documents them is idea. This means that `IMiscellaneousOperations` contains a few image functions that need to be moved.

```C#
CommitContainerChangesAsync
GetImageAsTarballAsync
GetImagesAsTarballAsync
LoadImageFromTarballAsync
LoadImageFromTarballAsync
BuildImageFromDockerfileAsync
```

**Comment by jonso4** [comment]
How do you feel about this work item? I can implement this if no one else has taken it. Just a few notes:

GetImageAsTarballAsync should be ExportImageAsync
GetImagesAsTarballAsync should be ExportImageAsync (overloaded to taken a list of images)
LoadImageFromTarballAsync is already implemented

**Comment by jterry75** [comment]
I like all of the suggestions. `SaveImageAsync` and `SaveImagesAsync` and remove `LoadImageFromTarballAsync` since we already have `LoadImageAsync`

Thanks!

**Comment by jterry75** [comment]
This has been fixed.
