### ISSUE TITLE
Implement the Plugins API surface.

### ISSUE THREAD

**Issue by jterry75** [Microsoft/Docker.DotNet#163]
Need to add `IPluginOperations` endpoint with the following:

```C#
ListPluginsAsync();
GetPluginPrivilegesAsync();
InstallPluginAsync();
InspectPluginAsync();
RemovePluginAsync();
EnablePluginAsync();
DisablePluginAsync();
CreatePluginAsync();
PushPluginAsync();
ConfigurePluginAsync();
```

**Comment by jonso4** [comment]
I can take this one as well. However, I'm not sure how to generate the models for some new parameters / responses that we need, so I've been writing them on my own. Would you be able to show me how to generate these, or just quickly generate them and send a PR?

**Comment by m-barthelemy** [comment]
Hi,
Is this still planned for v3.126?

**Comment by galvesribeiro** [comment]
@jterry75 can you update the generated files? I could implement the APIs but I always struggle with Go codegen.

I need to find some time to create a codegen from the YAML spec instead of rely on Go source...

**Comment by jterry75** [comment]
How about you try this and tell me what else you need. Not really sure what is needed for the whole picture here but this should get you started: [Commit](https://github.com/jterry75/Docker.DotNet/commit/80dfa236ad9808dbf3e7e917e551f74f9672cd74)

**Comment by jterry75** [comment]
Mostly completed as of #298

**Comment by m-barthelemy** [comment]
Hi,

When calling `ConfigurePluginAsync()`, I get the following exception:

```
System.InvalidOperationException: No public properties attributed with [Docker.DotNet.QueryStringParameterAttribute] found on type Docker.DotNet.Models.PluginConfigureParameters
```
