### ISSUE TITLE
Proposal: CancellationToken support

### ISSUE THREAD

**Issue by jasoncouture** [Microsoft/Docker.DotNet#166]
Currently, there is no way to cancel pending requests.
Each method call making network calls to docker should accept a CancellationToken as an optional parameter.

Example:
```csharp
IContainerOperations.ListContainersAsync(ContainersListParameters parameters);
```
would be come either:
```csharp
// Optional Cancellation Token as parameter with default value
// (default(CancellationToken) == CancellationToken.None)
IContainerOperations.ListContainersAsync(ContainersListParameters parameters, 
    CancellationToken cancellationToken = default(CancellationToken));
```
or
```csharp
// Overload with mandatory Cancellation Token
IContainerOperations.ListContainersAsync(ContainersListParameters parameters);
IContainerOperations.ListContainersAsync(ContainersListParameters parameters, 
    CancellationToken cancellationToken);
```

**Comment by jasoncouture** [comment]
Would be willing to implement and submit PR, please let me know which way you'd like to go (optional parameter, or overload, and do you want to do or would PR be better route).

**Comment by swernli** [comment]
Looks like the docker client object in the code already supports an overload of MakeRequestAsync that takes a task cancellation token, so some of the methods use it and others don't (compare the invocation in https://github.com/Microsoft/Docker.DotNet/blob/1c3f468d35495396c7982de2d77508f16b5a6e36/src/Docker.DotNet/Endpoints/ContainerOperations.cs#L136 vs the one at https://github.com/Microsoft/Docker.DotNet/blob/1c3f468d35495396c7982de2d77508f16b5a6e36/src/Docker.DotNet/Endpoints/ContainerOperations.cs#L155).  I'm not sure why the original design supported cancellation for some operations but not others.  

If you'd like to plumb that through on all of them, we'd be happy to review that PR for inclusion.

**Comment by jasoncouture** [comment]
Alright, I'll work on this as soon as I get a chance. Thanks for the quick response!

**Comment by jasoncouture** [comment]
Do you mind if I include #168 in the same PR, or do you prefer them seperate?

**Comment by jterry75** [comment]
One is fine thanks!
