### ISSUE TITLE
Update CSPROJ files for latest VS 2017

### ISSUE THREAD

**Issue by jasoncouture** [Microsoft/Docker.DotNet#169]
Project does not build correctly in latest version VS 2017, this is due to the addition of default compile items, as outlined here: https://github.com/dotnet/core/blob/master/release-notes/1.0/sdk/1.0-rc3-default-compile-items.md

Need to add 
```xml
<PropertyGroup>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
</PropertyGroup>
```
to each .csproj file, this should not break existing versions and should allow the new versions to work correctly.

I have already made this change while doing #166 and #168, I will be submitting a pull request for all 3 issues shortly.

**Comment by galvesribeiro** [comment]
I've updated the projects and removed the nuget packages on #171. It has the proper update for the new format and not just `EnableDefaultCompileItems`

**Comment by jasoncouture** [comment]
Excellent, I will remove from my PR and close this.
