### ISSUE TITLE
Support for "docker save" and "docker import"?

### ISSUE THREAD

**Issue by pauldotknopf** [Microsoft/Docker.DotNet#175]
Not seeing it anywhere.

Is it available via the docker API, but just not exposed in this API?

**Comment by jterry75** [comment]
We didn't have a need for them in the work we were doing for `Docker-PowerShell`. Would you be interested in contributing them?

**Comment by jonso4** [comment]
I can contribute these!

**Comment by jterry75** [comment]
Deal that would be awesome!
