### ISSUE TITLE
create "up-for-grabs" label

### ISSUE THREAD

**Issue by chintans** [Microsoft/Docker.DotNet#178]
There are many enhancements listed in issues. Can you guys create "up-for-grabs" label for community to pick and enhancement and start working on it.

**Comment by JosephWoodward** [comment]
Great idea, could also add it to [http://up-for-grabs.net](http://up-for-grabs.net/#/) to further encourage community contributions.

**Comment by jasoncouture** [comment]
Yes that's awesome. I want to contribute, but I hate having to ask what to do next. And I don't like starting PR's without direction, as it sometimes leads to wasted effort.

**Comment by jterry75** [comment]
@jstarks - I am not a repo admin. Can you do this?

**Comment by jterry75** [comment]
I know a bit late but I finally got access to do this. Will start tagging things this way. Thanks!
