### ISSUE TITLE
SwarmOperations.CreateServiceAsync failed: "ContainerSpec: image reference must be provided"

### ISSUE THREAD

**Issue by ikkentim** [Microsoft/Docker.DotNet#180]
``` c#
   async Task<ServiceCreateResponse> ISwarmOperations.CreateServiceAsync(ServiceCreateParameters parameters, CancellationToken cancellationToken)
        {
            var data = new JsonRequestContent<ServiceCreateParameters>(parameters ?? throw new ArgumentNullException(nameof(parameters)), this._client.JsonSerializer);// <<< THIS LINE
            var response = await this._client.MakeRequestAsync(new[] { SwarmResponseHandler }, HttpMethod.Post, "services/create", null, RegistryAuthHeaders(parameters.RegistryAuth), data, cancellationToken).ConfigureAwait(false);
            return this._client.JsonSerializer.DeserializeObject<ServiceCreateResponse>(response.Body);
        }
```

It sends the whole parameters as the request content, but it should only send the `ServiceSpec` in `parameters.Service`, causing Docker to return the error "ContainerSpec: image reference must be provided".

I'm not sure if this also happens in `ContainerOperations`, it does also pass on the whole `ServiceCreateParameters`. I've been unable to test this (maybe someone else can check that?)

**Comment by jterry75** [comment]
Thanks for the report. I verified all the other objects that pass as body content for this bug. It only affects the two areas in Swarm.
