### ISSUE TITLE
CreateImageAsync takes forever to pull an image

### ISSUE THREAD

**Issue by jchannon** [Microsoft/Docker.DotNet#183]
**Output of `dotnet --info`:**

```
.NET Command Line Tools (1.0.0-preview2-1-003177)

Product Information:
 Version:            1.0.0-preview2-1-003177
 Commit SHA-1 hash:  a2df9c2576

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64

```

**What version of Docker.DotNet?:**

```
2.124.3
```

**Steps to reproduce the issue:**
1.
```
                   var statusUpdate = this.dockerClient.Images.CreateImageAsync(new ImagesCreateParameters { Parent = "myimage", Tag = "latest" }, null).Result;
                    using (var reader = new StreamReader(statusUpdate))
                    {
                        string line;
                        while ((line = reader.ReadLine()) != null)
                        {
                            Console.WriteLine(line);
                        }
                    }
```

**What actually happened?:**
It takes absolutely ages to pull an image. If I do it in the terminal via `docker pull myimage:latest` it pulls it within a reasonable time.

**What did you expect to happen?:**
To take the same time as the terminal.

**Additional information:**
I actually think its doing extra work somehow. Doing a docker pull in the terminal tells me I have the latest downloaded yet using CreateImageAsync seems to do a lot of work still trying to pull an image.

**Comment by robborden** [comment]
It sounds like you want to try PullImageAsync() instead of CreateImageAsync() which may be re-building a new image on the host, rather than pulling it from the registry.

**Comment by jchannon** [comment]
That did it. Thanks

**Comment by jterry75** [comment]
I will create a backlog item to comment these with respect to the `docker cli` verbage. We chose to use the REST API language which confuses literally everyone including myself all the time.
