### ISSUE TITLE
Want to contribute but would like some advice/guidance

### ISSUE THREAD

**Issue by robborden** [Microsoft/Docker.DotNet#185]
I am using a fork of this project in production.  I have already fixed or am in the process of completing several items on the issues list (and some that aren't) like the Volumes API surface and Registry V2 API support.  I have added missing functionality such as container renaming, and fixed various minor bugs.  

With that being said, I do not know if it is appropriate to issues PRs because I don't know if they were fixed in the way that the maintainers of this repo would want them fixed or, more importantly, I have had to convert some things back over to c#6 compatible code, which creates merge headaches.  

The main clash is the use of  the "expression ?? throw new exception()" syntax shortcut which is not available prior to c#7 (the ?? operator is but only with another expression on the right, not a "throw" statement).

In addition to these issues, I didn't necessarily plan ahead for contributing to this project so my commit history may not be clean and organized enough to be able to issue a PR and have that merge nicely as an isolated new feature.  Any advice you have on if/how I can  go about contributing this code would be very helpful.  I have never contributed to an upstream repository in the past.

**Comment by ikkentim** [comment]
I'm no maintainer of this project, but you could

- install VS17 on the side(if you haven't already), 
- create a fresh fork of this repo
- check the diffs between your modified fork and this repo and apply those back in the fresh fork (using c#7 if possible)
- i think it's best to create a PR per change (eg for implementing the volumes api or for the registry v2 api)

**Comment by jterry75** [comment]
@robborden - I am happy to help do the reviews for you to PR the changes up. You don't even need VS17 if you don't want but at least the latest .NET Core CLI would give you the ability to compile C# 7 syntax. If it is 100% a non starter I can do a very easy roslyn tool that converts all the expressions to C# 7 when they PR up for you. We can create a sub branch off master to PR your changes and I will do the fixups in that model before merging all the way to master. Just let me know.

If you link me to the fork I am happy to take a look at doing some diffs and seeing how far off we are on the merges.

**Comment by robborden** [comment]
Awesome, great to hear back and that we can work together to get these updates integrated.  I'm currently running VS2015 Professional which I obtained through the Microsoft Partner Portal.  I will look into my membership status and see if I can upgrade. I would be open to updating the .NET Core CLI, however I am writing all my code for dotnet core 1.1.  Does this not necessarily mean I am on a new enough .NET Core CLI to compile C#7 syntax? Would I have any trouble running c#7 syntax in this environment?


Here is my repo: https://github.com/coinigy/Docker.DotNet


I think I actually got all the Volume surface API into one commit.
https://github.com/coinigy/Docker.DotNet/commit/1bda0e5eea78c2d1f2886dedcb4014922cc12d07


In the most recent commit  I've showed fixes and comments which are necessary on some model files generated by the specgen golang tooling.  It is the fix for the volume issues mentioned here: https://github.com/Microsoft/Docker.DotNet/issues/177
https://github.com/coinigy/Docker.DotNet/commit/ce0f3ffb1a56b87e2600d08ac35ff35e5ec53478


This is where things get a little dicey ;)
In this commit there is a fix for a problem that was introduced with restart policies in Docker v1.13.0.  It should be the bottom two files. It is co-mingled with some other changes in a rogue commit -a incident. 
https://github.com/coinigy/Docker.DotNet/commit/0ab88df5254f695035c2abba561af0db454a1141

My experience was that the EnumMember values were/are not being used during serialization, and my containers were being created with a restart policy of UnlessStopped instead of unless-stopped (for example).  It seemed like Docker actually accepted/worked with these values for some reason before, even though it should not have.  Then they seemed to have fixed it in v1.13.0 which broke stuff for me.  This all seemed unusual so I'm not sure if I missed something along the way but adding an JsonConverter for serialization cleared up all my issues.  This is (again) changes to specgen generated code which probably makes integrating these changes challenging.


I've added "Rename" to the container operations here:
https://github.com/coinigy/Docker.DotNet/commit/9f448cedcd3426dd3cb297bf3737431d7a3a87e3
annnnnnnnd here (sigh): https://github.com/coinigy/Docker.DotNet/commit/2966cc4a2b9ba1936eb7f7a89444e4b9211a7281


Last, but certainly not least, I also have an open issue with regards to the Registry API surface which will need some attention/discussion here: 
https://github.com/Microsoft/Docker.DotNet/issues/186


Please let me know how you'd like me to proceed!  :D

**Comment by jterry75** [comment]
@robborden - Here is what I would do. I think it will be by far the easiest while still giving you the credit for the merges.

In your fork make a new topic branch per PR. So for example I will use your "RenameContainerAsync" addition.

```git
git checkout -b rename origin/master
git cherry-pick 9f448ce
git cherry-pick 2966cc4
# do any fixups if required based on master
git rebase HEAD~2 --interactive
# squash them to one commit.
git push <myforkremotename> rename:rename
# PR from myforkremotename/rename to master
```

I can do this for you by cherry-picking your changes across to my fork but I am worried that you wont get the credit

**Comment by robborden** [comment]
@jterry75 I think we should get this current crop of changes/updates merged (where applicable) using whatever means necessary.  I hadn't considered the credit previously, and it's really not of much consequence to me anyways.  Seeing my changes help this incredibly useful and powerful library move in the right direction is reward enough!

With that being said, I think it would work best for all involved if I create an intermediate fork between your repo and my existing fork.  This way I can ensure all changes are working properly in my application and then filter in just the relevant commits the way you demonstrated above and issue PRs from there.  This will make things easier and cleaner and allow me to merge upstream changes and work on  the repo without it impacting my application in any way.  This also clears up the c#6/7 issues, I'll just install VS2017 Community.

**Comment by jterry75** [comment]
Perfect! Thanks again for the help here!

**Comment by robborden** [comment]
Hi jterry75,

I just wanted to make sure that we're on the same page per the above.  I was expecting you were going to manually merge the changes I already did that are outlined above, and then in future contributions I would issue PRs from a separate fork.  If you are just busy/delayed, no problem, just checking in.  

Any way I can get generated model files for Registry v2 API so I can start working on that?  (https://github.com/Microsoft/Docker.DotNet/issues/186)

**Comment by jterry75** [comment]
Oh. Good thing you said something. I thought you were going to PR them. I will for sure merge these next week then.

As far as the Registry, I looked into that some while back and couldn't see that they have the same type descriptions in the go files. Or at least I couldn't find them so I am unsure how to do this but will investigate more next week.

**Comment by pwdst** [comment]
Has this merge slipped through the cracks @jterry75 - I was going to create a PR to add RenameContainer support and searched open issues to see if there was an open issue to create it against when I found this one. I can of course continue to create the PR which I don't think will involve much work, but I don't want to duplicate @robborden's effort or take his credit.

**Comment by jterry75** [comment]
Looks like this did slip. PR' up: #245 (Thanks Rob!). As for Registry. I am almost done here but that will be tracked in #165. Are there any other outstanding issues here?

**Comment by robborden** [comment]
Nothing else that I know of but I will double-check and issue a separate
pull request for it if there is anything.

**Comment by jterry75** [comment]
Ok thanks!
