### ISSUE TITLE
Any way to get generated model files for v2 Registry API?

### ISSUE THREAD

**Issue by robborden** [Microsoft/Docker.DotNet#186]
I am looking at submitting a PR to include the Docker v2 Registry in this repo, however the repo is currently lacking the generated model files.  I created my own but they're incomplete and it would be a lot easier if I could get them somehow.

**Comment by jterry75** [comment]
Alright I spent some time yesterday. I don't exactly have the time to implement the registry for you but I implemented the interfaces and models from reading the spec. I think that these are correct. Would you be willing to implement the backing classes if I give you a commit id for the interfaces?

**Comment by robborden** [comment]
Absolutely, just point me in the right direction.

**Comment by robborden** [comment]
@jterry75 Have you commited these interfaces/models somewhere yet?

**Comment by jterry75** [comment]
Lets track this work in #186. Closing for now. Will update that thread.
