### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by myagley** [Microsoft/Docker.DotNet#203]
Are there plans to do a new release soon? There appears to be a pretty big gap between `2.124.3` and `HEAD`.

**Comment by ikkentim** [comment]
ping @jterry75

**Comment by ikkentim** [comment]
ping @swernli

**Comment by markrendle** [comment]
ping @ahmetb perhaps?

**Comment by galvesribeiro** [comment]
Yeah, there is a gap. I'm working on bring the missing APIs for the current version first, then update to use the new API surface. Maybe after that we have a bunch of news all togheter to make a new release.

**Comment by jterry75** [comment]
Sorry all. I was out for a while. I am working on investigating a few bug's then will get the release out to nuget

**Comment by jterry75** [comment]
This has now been completed and published to nuget. Release [notes](https://github.com/Microsoft/Docker.DotNet/releases/tag/3.125.0).
