### ISSUE TITLE
Is DotNet Core 1.0 supported?

### ISSUE THREAD

**Issue by genifycom** [Microsoft/Docker.DotNet#208]
**Output of `dotnet --info`:**
.NET Command Line Tools (1.0.4)

Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.4

**What version of Docker.DotNet?:**
2.124.3

**Steps to reproduce the issue:**
1.   <ItemGroup>
    <PackageReference Include="Docker.DotNet" Version="2.124.3" />
    <PackageReference Include="Microsoft.AspNetCore" Version="1.0.5" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="1.0.4" />
    <PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="1.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer.Design" Version="1.0.4" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="1.0.2" />
    <PackageReference Include="Microsoft.VisualStudio.Web.BrowserLink" Version="1.0.1" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="1.0.1" />
  </ItemGroup>

2. Use the examples given on https://github.com/Microsoft/Docker.DotNet under Usage
3. Compiler gives
The type or namespace name 'ContainerResponse' could not be found (are you missing a using directive or an assembly reference?)
Cannot implicitly convert type 'System.Collections.Generic.IList<Docker.DotNet.Models.ContainerListResponse>' to 'System.Collections.Generic.IList<ContainerResponse>'. An explicit conversion exists (are you missing a cast?)
Argument 2: cannot convert from 'Docker.DotNet.Models.HostConfig' to 'Docker.DotNet.Models.ContainerStartParameters'

**What actually happened?:**
Compiler errors

**What did you expect to happen?:**
Expected Usage example to compiler and run.

**Additional information:**
Visual Studio Enterprise 2017 version 15.2

**Comment by Camble** [comment]
I think the readme has a typo. Try ContainerListResponse instead.

**Comment by Camble** [comment]
I think there is a typo in the readme. Try IList<ContainerListResponse> instead.

**Comment by alexgwolff** [comment]
Try this pull : #216
