### ISSUE TITLE
How do I run a command on a container?

### ISSUE THREAD

**Issue by marcuslindblom** [Microsoft/Docker.DotNet#212]
How can I run this command using the docker dotnet remote api? `docker run jrottenberg/ffmpeg -i url -c:a copy -f mjpeg -preset ultrafast -an -c:v mjpeg -vf "select='not(mod(n\\,29))',yadif,scale=480:-1,crop=iw:270,tile=1x50" -q:v 20 -vframes 1 - > out.jpg`

**Comment by swernli** [comment]
Unfortunately, the docker CLI options are not always 1:1 with the actual daemon remote API, so I'm not sure how that specific cmdline translates into a series of daemon calls.  Perhaps you could try running either the CLI or your daemon (or both) in debug mode and watch what remote API endpoints are invoked and what JSON is provided so that you begin finding the correct daemon equivalents for the options you use above.

**Comment by marcuslindblom** [comment]
@swernli If I understand correctly from the documentation I need to create the container, start the container and then attach to the container. I also need to add some additional parameters to the run command. I think this is done by passing CreateContainerParameters(config) to the CreateContainerAsync method like this:

```c#
var parameters = new Config {
  Image = "d5db001b2b8a",              
  ArgsEscaped = true,
  AttachStderr = true,
  AttachStdin = true,
  AttachStdout = true,              
  Cmd = new string[] { " -i http://foobar.com -c:a copy -f mjpeg -preset ultrafast -an -c:v mjpeg -vf \"select='not(mod(n\\,29))',yadif,scale=480:-1,crop=iw:270,tile=1x50\" -q:v 20 -vframes 1 pipe:1" }
};

CreateContainerResponse response = await client.Containers.CreateContainerAsync(new CreateContainerParameters(parameters));
```
When the container is created I start and attach to it like this:
```c#
Task task = client.Containers.StartContainerAsync(response.ID, new ContainerStartParameters());

var config = new ContainerAttachParameters {
  Stream = true,
  Stderr = true,
  Stdin = false,
  Stdout = true,
  Logs = "1"
};   

var buffer = new byte[1024];
using (var stream = await client.Containers.AttachContainerAsync(response.ID, false, config, default(CancellationToken)))
{
    var result = await stream.ReadOutputAsync(buffer, 0, buffer.Length, default(CancellationToken));
    do
    {
        Console.Write(Encoding.UTF8.GetString(buffer, 0, result.Count));
    }
    while (!result.EOF);
}
```
The container seems to start by the Cmd does not run, probably because it's not the correct way of adding additional parameters to the run command? Have I missed something obvious?

Another question, when I run the command from the terminal the container stops after running the command but with this command it keeps on reading from the output forever. Do I need to stop the container my self or what am I missing?

**Comment by marcuslindblom** [comment]
This seems to work for me:

```c#
            var client = new DockerClientConfiguration(new Uri("unix:///var/run/docker.sock")).CreateClient();

            var parameters = new Config {
              Image = "d5db001b2b8a",              
              ArgsEscaped = false,
              AttachStderr = false,
              AttachStdin = false,
              AttachStdout = true,
              Cmd = new string[] {
                "-i", "http://foobar.com/videomp4",
                "-c:a", "copy",
                "-f", "mjpeg",
                "-c:v", "mjpeg",
                "-vf", "select='not(mod(n\\,29))',yadif,scale=480:-1,crop=iw:270,tile=1x50",
                "-q:v", "20",
                "-frames:v", "1",
                "pipe:1"
              }
            };

            CreateContainerResponse response = await client.Containers.CreateContainerAsync(new CreateContainerParameters(parameters));

            Task task = client.Containers.StartContainerAsync(response.ID, new ContainerStartParameters());

            var config = new ContainerAttachParameters {
              Stream = true,
              Stderr = false,
              Stdin = false,
              Stdout = true
            };   

            var buffer = new byte[1024];
            using (var stream = await client.Containers.AttachContainerAsync(response.ID, false, config, default(CancellationToken)))
            {
              using (var fileStream = System.IO.File.Create($"{DateTime.Now.Ticks}.jpg"))
              {
                await stream.CopyOutputToAsync(null, fileStream, null, default(CancellationToken));
              }
            }
```

**Comment by swernli** [comment]
@marcuslindblom Seems like you are on the right track.  One thing to note is that performing the attach after the start leaves a window where the process may have already exited (if it runs fast enough) before the attach goes through.  It turns that docker avoids this in their client by performing the attach before the start, which is what our PowerShell cmdlets do as well.  Those cmdlets use Docker.DotNet quite extensively, so would be a good reference for the patterns we've found work for us.  In particular, see https://github.com/Microsoft/Docker-PowerShell/blob/ef86a996f95e2f6c369a6fe58d68bffafb120b5b/src/Docker.PowerShell/Objects/ContainerOperations.cs#L158 for how the cmdlet helper library handles starting and potentially attaching to a container.

**Comment by marcuslindblom** [comment]
@swernli I changed my code to the pattern you referred to but if I don't start the container "twice" I don't get any output from the stream?

This is what I use now:
```c#

internal static async Task StartContainerAsync(
    DockerClient client,
    string containerId,
    ContainerAttachParameters attachParams,
    bool? isTTY,
    ContainerStartParameters startParams,
    CancellationToken token)
{
    MultiplexedStream stream = null;
    Task streamTask = null;

    try
    {
        if (attachParams != null)
        {
            stream = await client.Containers.AttachContainerAsync(containerId, isTTY.GetValueOrDefault(), attachParams, token);
            using (var fileStream = System.IO.File.Create($"{DateTime.Now.Ticks}.jpg"))
            {                        
                streamTask = stream.CopyOutputToAsync(null, fileStream, null, default(CancellationToken));
            }                    
        }

        if (!await client.Containers.StartContainerAsync(containerId, new ContainerStartParameters()))
        {
            throw new Exception("The container has already started.");
        }

        if (attachParams != null)
        {
            await streamTask;
        }
    }
    finally
    {
        stream?.Dispose();
    }
}
```
And this is how I use the new command:
```c#
var client = new DockerClientConfiguration(new Uri("unix:///var/run/docker.sock")).CreateClient();

var createContainerParameters = new Config {
  Image = "d5db001b2b8a",              
  ArgsEscaped = false,
  AttachStderr = false,
  AttachStdin = false,
  AttachStdout = true,
  Cmd = new string[] {
    "-i", "https://.../original.mp4",
    "-c:a", "copy",
    "-f", "mjpeg",
    "-c:v", "mjpeg",
    "-vf", "select='not(mod(n\\,29))',yadif,scale=480:-1,crop=iw:270,tile=1x50",
    "-q:v", "20",
    "-frames:v", "1",
    "pipe:1" // pipe output to stdout
  }
};

CreateContainerResponse response = await client.Containers.CreateContainerAsync(new CreateContainerParameters(createContainerParameters));

====> If I don't include this line I don't get any output from the stream? <====
//Task task = client.Containers.StartContainerAsync(response.ID, new ContainerStartParameters());

var config = new ContainerAttachParameters {
  Stream = true,
  Stderr = false,
  Stdin = false,
  Stdout = true
};   

Task streamTask = ContainerOperations.StartContainerAsync(client, response.ID, config, false, new ContainerStartParameters(), default(CancellationToken));
```
Any idea what's going on here?

**Comment by swernli** [comment]
@marcuslindblom  That is definitely odd... I would expect this pattern to work without the need for the extra start.  Can you try setting `AttachStderr` in your container config to true and then doing the same with `Stderr` in the attach parameters?  I did notice that our cmdlets always set both stdout and sterr to true for both the container and for attach, which matches what the docker client does.  

As a shot in the dark, is it possible the container itself only works the second time? I'm not sure what it is you are running inside of the container, but you could try running your command via the docker cmdline on a fresh container and confirm that it produces output the first time and not just the second time.

**Comment by marcuslindblom** [comment]
@swernli I finally got this working using the following code.

```c#
internal static async Task<Stream> StartContainerAsync(
    DockerClient client,
    string containerId,
    ContainerAttachParameters attachParams,
    bool? isTTY,
    ContainerStartParameters startParams,
    CancellationToken token)
{
    MultiplexedStream stream = null;
    Task streamTask = null;
    Stream stdOutputStream = new MemoryStream();

    try
    {
        if (attachParams != null)
        {
            stream = await client.Containers.AttachContainerAsync(containerId, isTTY.GetValueOrDefault(), attachParams, token);
            streamTask = stream.CopyOutputToAsync(null, stdOutputStream, null, default(CancellationToken));
        }

        if (!await client.Containers.StartContainerAsync(containerId, new ContainerStartParameters()))
        {
            throw new Exception("The container has already started.");
        }

        if (attachParams != null)
        {
            await streamTask;
        }
        return stdOutputStream;
    }
    finally
    {
        stream?.Dispose();
    }
}
```

This code also returns the the stdout from the container output.

How can I write data to stdin with this method?

I tried adding the following line after:
`stream = await client.Containers.AttachContainerAsync(containerId, isTTY.GetValueOrDefault(), attachParams, token);`

```c#
await stream.WriteAsync(input, 0, input.Length, default(CancellationToken));
```
But it seems like I'm getting an error but I can't catch the error? Can you give me an example on how to write input to stdin and still be able to receive the output from stdout?

**Comment by marcuslindblom** [comment]
Closing and open a new issue regarding the last issue. https://github.com/Microsoft/Docker.DotNet/issues/223
