### ISSUE TITLE
Implement the Network API surface

### ISSUE THREAD

**Issue by monubamb** [Microsoft/Docker.DotNet#219]
Can we add INetworkOperations endpoint with the following:

ConnectNetworkAsync();
CreateNetworkAsync();
DisconnectNetworkAsync();
InspectNetworkAsync();
RemoveNetworkAsync();
ListNetworkAsync();

**Comment by swernli** [comment]
Does the existing INetworkOperations not meet your needs somehow? It looks like it has all the methods you are asking for (RemoveNetworkAsync is instead called DeleteNetworkAsync).  See this existing functionality:
https://github.com/Microsoft/Docker.DotNet/blob/f13b3f52fc623d9331469422134649bac6579002/src/Docker.DotNet/Endpoints/INetworkOperations.cs

**Comment by monubamb** [comment]
Thanks. Please close the issue. I did not notice that Networking API are already in place. One question I had though was whether networking API would work agnostic of Swarm/Services. For example in case of Service Fabric, we can deploy containers with compose/NAT. Would these API's work in that construct as well?

**Comment by galvesribeiro** [comment]
@monubamb I think so. The Networking endpoints talk to the Docker Engine API, not ServiceFabric. I'm not aware of how SF deal with networking in Docker but, as long as it can use the connections available in the engine, it should work.
