### ISSUE TITLE
Unable to connect to Windows Docker Engine

### ISSUE THREAD

**Issue by gaui** [Microsoft/Docker.DotNet#220]
**Output of `dotnet --info`:**

```
$ dotnet --info
.NET Command Line Tools (1.0.4)

Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.4
```

**What version of Docker.DotNet?:**

```
NuGet 2.124.3
```

**Steps to reproduce the issue:**
1. Create a DockerClient with connection to `npipe://./pipe/docker_engine` or `tcp://localhost:2375`

**What actually happened?:**

With `npipe://./pipe/docker_engine` I get a timeout:

```
Unhandled Exception: System.AggregateException: One or more errors occurred. (The operation has timed out.) ---> System.TimeoutException: The operation has timed out.
   at System.IO.Pipes.NamedPipeClientStream.ConnectInternal(Int32 timeout, CancellationToken cancellationToken, Int32 startTime)
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
```

With `tcp://localhost:2375` I get a failed connection:

```
Unhandled Exception: System.AggregateException: One or more errors occurred. (Connection failed) ---> System.Net.Http.HttpRequestException: Connection failed ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException: Connection refused [::ffff:127.0.0.1]:2375
   at Microsoft.Net.Http.Client.ManagedHandler.<TCPSocketOpener>d__37.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
```

And yes, I added the `-p 2375:2375` in `docker run`

**What did you expect to happen?:**

Get a connection and be able to listen to Docker events.

**Additional information:**

I have enabled exposure of localhost:2375 in Docker settings. See below:

![Docker Settings](http://i.imgur.com/CrkRWZC.png)

**Comment by liqdfire** [comment]
` Connection refused [::ffff:127.0.0.1]:2375`

That error is telling you that `localhost` is resolving to an IPv6 address on your system, I am not sure the daemon is binding to ipv6, it is probably binding to the ipv4 `127.0.0.1`

Try connecting to `tcp://127.0.0.1:2375`

Also, using `-p 2375:2375` in your docker run is trying to map the port 2375 on the system to port 2375 inside the container you are trying to run, that is not impacting the ports the docker daemon is listening on.
See [https://docs.docker.com/engine/reference/commandline/run/#publish-or-expose-port--p-expose](url) for more information on exposing ports on a container.

**Comment by gaui** [comment]
@liqdfire Thanks for the answer. I honestly don't know why it says `[::ffff:127.0.0.1]` because I'm not using IPv6 and have a static IPv4 assigned to my DockerNAT network adapter.

nmap on the host:

```
$ nmap -p 2375 127.0.0.1

Starting Nmap 7.50 ( https://nmap.org ) at 2017-06-28 00:17 Greenwich Standard Time
Nmap scan report for www.007guard.com (127.0.0.1)
Host is up (0.00s latency).

PORT     STATE SERVICE
2375/tcp open  docker

Nmap done: 1 IP address (1 host up) scanned in 1.23 seconds
```

By the way, I tried to add `EXPOSE 2375` to my Dockerfile. Didn't work either.

**Comment by liqdfire** [comment]
I do not completely understand what it is your are trying to accomplish, how you are attempting your connection is a big ambiguous. Are you running the application on your machine native, or are you running it inside a container trying to connect to the daemon?

You should not be exposing port 2375, or mapping it with a -p when running a container. Both of those actions tells the docker daemon to bind the container to that port at the host level. If you have exposed the daemon on port 2375, the port would already be in use and cannot be used for listening by the application inside the container.

**Comment by gaui** [comment]
@liqdfire Hehe, I'm running my application inside a container trying to connect to the daemon on the host. On a Linux host you mount a volume to the docker.sock file, and use that, but I'm not sure how to do it on a Windows host - and been unsuccessful with my attempts.

Here's my code: https://github.com/gaui/docker-notifier

**Comment by liqdfire** [comment]
Ok, that makes a bit more sense. I am pretty sure you cannot connect to 127.0.0.1 or localhost when running the container in docker for windows. 

You have to keep in mind that with docker for windows, the containers are actually running inside a linux vm under hyper-v, so 127.0.0.1 or localhost for those containers would be relative to the vm. The connection from windows to the vm for networking is done via a nat network setup in hyper-v, where windows has a default static ip of 10.0.75.1. You might try connecting to 10.0.75.1, make sure you either have that port open in windows firewall for public networks if you have windows firewall on. You would not want to hard code the connection ip, as an advanced user could change the static ip for windows in the gui client, might want to pass it in as an environment variable.

You are correct about mapping the .socket in linux, though mounting a volume to make the connection in linux is completely different from exposing or publishing a tcp/ip port. Mounting the volume basically makes a virtual mount point to the file on the local machine, which your container app can then interact with. Publishing or exposing a port binds the container to the port on the physical host, you cannot have more than 1 application using a port at a time.

**Comment by gaui** [comment]
@liqdfire I'm not sure you follow. I'm trying to connect FROM the container TO the host daemon. The docker-notifier application is running in .NET Core inside a Docker container running on a Windows host. I'm trying to use Docker.DotNet to get Docker events from the host.

**Comment by liqdfire** [comment]
Ah, but the container is not running on the windows host. It is running inside a linux vm hosted under hyper-v on the windows host.

**Comment by gaui** [comment]
@liqdfire But that's what I'm trying to achieve, to connect to the Docker Engine. I'm able to connect to it on Linux via docker.sock but how can I achieve this on Windows? I've tried named pipes and tcp://localhost:2375 but no success.

**Comment by liqdfire** [comment]
Instead of connecting to tcp://127.0.0.1:2375, make your connection to tcp://10.0.75.1:2375

**Comment by liqdfire** [comment]
![image](https://user-images.githubusercontent.com/328512/27766276-37e5c758-5e99-11e7-9fcb-9b567605a4be.png)

when running containers on windows, the daemon is not actually listening on port 2375. The daemon is running inside the linux vm, and a proxy application is running on the windows host. The proxy application is what is listening on port 2375, and forwards the requests to the daemon in the vm.

Your application inside the container cannot talk directly to the daemon via port 2375. It must make a tcp connection out to the windows host, and connect to the docker proxy.

**Comment by liqdfire** [comment]
Looks like 10.0.75.1 is not the correct answer either.

https://github.com/docker/for-win/issues/37

You should use tcp://docker.for.win.localhost:2375

**Comment by gaui** [comment]
Thank you @liqdfire  `tcp://docker.for.win.localhost:2375` works. I'll close this issue.
