### ISSUE TITLE
Is there a Docker Compose API?

### ISSUE THREAD

**Issue by sebagomez** [Microsoft/Docker.DotNet#222]
I'm sorry but I can't seem to find it... even in the Docker API Reference, there's nothing about Docker Compose. Can somebody point out a useful link or two?

**Comment by galvesribeiro** [comment]
I asked myself the same thing when I was starting with Docker. The answer is No, unfortunately. 

`docker-compose` is a client thing and as much as we are going more and more deeper on Swarm and Services/Tasks, I don't see IMHO that compose will ever hit the servers.

**Comment by sebagomez** [comment]
Ok, I'm not that deep into Docker to completely understand your answer. 
But at least I understood the short answer 😃
Thanks mate

**Comment by galvesribeiro** [comment]
@sebagomez sorry. What I meant is that, `docker-compose` command line and the `.yml` is a Docker CLI feature so it run on the client side, not in Docker engine itself. Hence why Docker API and Docker.Dotnet don't have support for it.

IMHO, I see that `docker-compose` is not something that will stay around for much longer.

**Comment by sebagomez** [comment]
Oh ok, I see.
And do you see anything at the engine level that will replace `docker-compose` ?

**Comment by galvesribeiro** [comment]
Well, you may always define a single Dockerfile and create a Swarm Service from it. It will define replicas and you can use overlay networks to communicate with other services inside a Swarm cluster.

**Comment by sebagomez** [comment]
Ok, one more question since you've been so nice, say I need the aspnet image and the sql-server-express images... how do I integrate them in a single file. Do I have to create one single dockerfile with what these two have? Like `FROM windowsservercore` and then add IIS, and install SQL Server, which would replicate exactly what their Dockerfiles have. Or is it a better way I'm not familiar with?

**Comment by galvesribeiro** [comment]
Yeah, AFAIK, there is no *merge* operation on images unfortunately. You will have to get the base common image and make yours `FROM` it, and then reapply the layers manually on your dockerfile.

**Comment by sebagomez** [comment]
Your too kind... thanks for all the tips and help
