### ISSUE TITLE
GetSystemInfoAsync() doesn't work!

### ISSUE THREAD

**Issue by Raffa50** [Microsoft/Docker.DotNet#225]
Hello I'm trying to get docker.net to work
I want to get info, like the command: docker info

I've tryed: info = client.Miscellaneous.GetSystemInfoAsync().Result;
also tryed running my program (and VS) with admin rights but it still don't work,
i get no exceptions the program doesn't terminate :'(
However await client.Miscellaneous.PingAsync(); works

**Comment by galvesribeiro** [comment]
That is weird @Raffa50 

If you put it in a `try/catch` it still not throw an exception? I'm using this method without problems...

**Comment by Raffa50** [comment]
yeah it was in a try catch... maybe is my pc... it needs a cleanup? I'll try on my other pc

**Comment by Raffa50** [comment]
It works in a console application, but not in a Windows Forms Application, you know why?

**Comment by Raffa50** [comment]
solved: function that communicate with docker need to run on a different thread (not form thread)
a backgroundworker is fine!

**Comment by galvesribeiro** [comment]
@Raffa50 that is weird... There are `XXXAsync()` methods which should be fine to be called from the main thread, as long as you make the method `async` and call with `await XXXAsync()`.

What may be happening with you, is that you are calling `XXXAsync().Wait()` or `XXXAsync().Result`. That will block the current thread.

**Comment by ikkentim** [comment]
> What may be happening with you, is that you are calling XXXAsync().Wait() or XXXAsync().Result. That will block the current thread.

That's what he's doing wrong

op:
> I've tryed: info = client.Miscellaneous.GetSystemInfoAsync().Result;
