### ISSUE TITLE
[proposed feature request] Support private Azure registry 

### ISSUE THREAD

**Issue by masroorhasan** [Microsoft/Docker.DotNet#230]
We need to expand support for private registries and build on top of supporting just docker registry. Proposing feature request to support Azure private registry:
https://docs.microsoft.com/en-us/rest/api/containerregistry/ 

Azure registry has a REST API support thus it would be require a wrapper for new registry type. Usage would entail specifying registry source with the same AuthConfig that specifies auth parameters.

**Comment by jterry75** [comment]
Maybe I need to look into it more but can you provide more info. This API is for registry management as far as I can tell which is a separate area of concern from Docker API's itself. I would assume (possibly incorrectly) that as far as `docker login, pull, push` is concerned it would expose the same API correct? So what needs to be custom? Just `Authentication`?

**Comment by masroorhasan** [comment]
Thanks Justin. 

In the documentation, under the "Create an image by pulling from Docker Registry", the code "pulls fedora/memcached image to your Docker instance using your Docker Hub account".

Was wondering if we can add support to specify the url of the registry to pull the image from. In this scenario it would be a private registry hosted on Azure. The feature could be expanded to support private registries in general (instead of always interfacing with docker registry). The AuthConfig could still be used for authenticating to whichever registry we want to point to.

I didn't see any example of this being possible so I could be wrong. Let me know if that makes sense :)

**Comment by galvesribeiro** [comment]
@masroorhasan, like @jterry75 mentioned there are 2 APIs:

1. Docker CLI/Client/API -> `login, pull, push` -> We already have it. However, I think we still miss Registry v2 APIs and there is and issue (#165) which should be tackle sometime in the future.
2. Docker Registry Management API -> That is out of scope of the client. I think that maybe if @jterry75 want, we could add an extra class (not codegenerated) to talk to it.

In all cases, we support "private registries" already.

**Comment by jterry75** [comment]
@galvesribeiro -  I am almost done with 1. #165 but need a few more days to test.

**Comment by masroorhasan** [comment]
@jterry75 @galvesribeiro Thanks for the responses - I'll try to hook it up with Azure registry and let you know. I think this issue can be close since it looks like a duplicate of #165 :)
