### ISSUE TITLE
Local ports run out after repeatedly call docker api

### ISSUE THREAD

**Issue by 303248153** [Microsoft/Docker.DotNet#233]
Refer to #232 , I changed DockerClient to singleton but it still cause local ports run out.

Code:

``` csharp
public async Task StartKeepaliveLoop()
{
    var client = dockerClientConfiguration.CreateClient();
    while (true)
    {
        await client.Miscellaneous.GetVersionAsync();
        await Task.Delay(1000);
    }
}
```

![close_waits](https://user-images.githubusercontent.com/16222094/28444316-e15f475a-6dee-11e7-9bf6-751383c6a49e.png)

Also I can reproduce this problem on my local machine:

![1](https://user-images.githubusercontent.com/16222094/28445374-9b47d220-6df6-11e7-8606-1fcae02dff57.png)

**Comment by galvesribeiro** [comment]
Please check my reply https://github.com/Microsoft/Docker.DotNet/issues/232#issuecomment-316878633

**Comment by 303248153** [comment]
@galvesribeiro 
Please look the code I post in this issue, I **did** reuse the client but it still cause many CLOSE_WAIT connections, I think the internal sockets is not closed at all.

**Comment by galvesribeiro** [comment]
I see. I'm not sure why it is generating a new internal socket for each of your requests... It should be the same socket...
