### ISSUE TITLE
InitSwarmAsync exception message reads "Node is not part of a swarm." when already in a swarm.

### ISSUE THREAD

**Issue by aemery** [Microsoft/Docker.DotNet#237]
**Output of `dotnet --info`:**

```
.NET Command Line Tools (2.0.0-preview2-006497)

Product Information:
 Version:            2.0.0-preview2-006497
 Commit SHA-1 hash:  06a2093335

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0-preview2-006497\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview2-25407-01
  Build    : 40c565230930ead58a50719c0ec799df77bddee9
```

**What version of Docker.DotNet?:**

Built from the repo as of today. Last commit by the time I built: https://github.com/Microsoft/Docker.DotNet/commit/d3a4f96e26ee7e08a598543a94f019b7bbe5df1e

**Steps to reproduce the issue:**
1. Call InitSwarmAsync.
2. Call InitSwarmAsync again.

**What actually happened?:**
The exception thrown contains the following message: "Node is not part of a swarm."

**What did you expect to happen?:**
The message should be "Node is already part of a swarm." as specified in the documentation of the InitSwarmAsync method in ISwarmOperations. 

**Additional information:**
The API of InitSwarmAsync call uses the same SwarmResponseHandler as other calls which handles 503s with this message. It should define its own handler the same way as JoinSwarmAsync.

**Comment by galvesribeiro** [comment]
Hello @aemery 

Looks like the only error handler throw this message as you can see in the code here https://github.com/Microsoft/Docker.DotNet/blob/ebf4e3fa15106874493add991a668c1f8def29da/src/Docker.DotNet/Endpoints/SwarmOperations.cs#L20

I'm not in a PC right now, but will check what are the options from Docker API doc when I get home and fix it.

**Comment by aemery** [comment]
Have a look at JoinSwarmAsync. The same way to handle the 503 as in there will fix this bug.

**Comment by q-bertsuit** [comment]
I ran into this issue, but now the problem is that no exceptions are thrown at all. If you try to call InitSwarmAsync twice, it simply returns null. Looks like the code only checks for HttpStatusCode.NotAcceptable. All other errors result in returning null
