### ISSUE TITLE
LeaveSwarmAsync throws when calling with SwarmLeaveParameters != null

### ISSUE THREAD

**Issue by aemery** [Microsoft/Docker.DotNet#238]
**Output of `dotnet --info`:**

```
.NET Command Line Tools (2.0.0-preview2-006497)

Product Information:
 Version:            2.0.0-preview2-006497
 Commit SHA-1 hash:  06a2093335

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0-preview2-006497\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview2-25407-01
  Build    : 40c565230930ead58a50719c0ec799df77bddee9
```

**What version of Docker.DotNet?:**

```
Built from the repo as of today. Last commit by the time I built: d3a4f96
```

**Steps to reproduce the issue:**
1. Call LeaveSwarmAsync with Force = true

Client.Swarm.LeaveSwarmAsync(new SwarmLeaveParameters {
    Force = true
})

**What actually happened?:**
Message: System.AggregateException : One or more errors occurred. (No public properties attributed with [Docker.DotNet.QueryStringParameterAttribute] found on type Docker.DotNet.Models.SwarmLeaveParameters.)

The property Force of SwarmLeaveParameters is not defined as a QueryStringParameter (see SwarmLeaveParameter.Generated.cs) and is used a type of a QueryString (see ISwarmOperations.LeaveSwarmAsync) which throws when the QueryString checks for attributes of type QueryStringParameter (QueryString.cs line 106).

**Comment by jterry75** [comment]
Just an oversight in specgen.go. Fixing.
