### ISSUE TITLE
Can't Access Build From Docker File Method

### ISSUE THREAD

**Issue by MaxLFarrell** [Microsoft/Docker.DotNet#242]
**Output of `dotnet --info`:**

```
.NET Command Line Tools (1.0.0)

Product Information:
 Version:            1.0.0
 Commit SHA-1 hash:  e53429feb4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16215
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0
```

**What version of Docker.DotNet?:**

```
2.124.3
```

**Steps to reproduce the issue:**
1. Install Docker.DotNet v2.124.3 by adding it to .net core csproj file
2. Instantiate Docker Client
3. Attempt to reference BuildImageFromDockerfileAsync

Relevant Code:
```
DockerClient client;
client = new DockerClientConfiguration(new Uri("http://x.x.x.x:4243"))
                .CreateClient();
client.Images.BuildImageFromDockerfileAsync("");
```

**What actually happened?:**
I am told:
`IImageOperations does not contain a definition for BuildImageFromDockerfileAsync`

**What did you expect to happen?:**
To be able to use the method.

**Comment by jterry75** [comment]
There has been a lot of "moving" in an attempt to align with the Docker API documentation closer. While this is under `Images` now it used to be under `Miscellaneous`. So `client.Miscellaneous.BuildImageFromDockerfileAsync("");` in v2.124.3

**Comment by MaxLFarrell** [comment]
Thank you very much. Secondary question (let me know if I should open a new issue for this) is there more extensive documentation for this library somewhere or is the readme and the code comments all of it?

**Comment by jterry75** [comment]
There is not anything other than the comments. What would you like to see here? I am open to adding documentation where helpful for sure.

At least for the release coming in the next few days I have tried to re-align very closely to the Docker [Remote API v1.25](https://docs.docker.com/engine/api/v1.25/) design. IE: This is a REST wrapper of that API but no more logic or simplicity to document.

**Comment by MaxLFarrell** [comment]
Let me work up a little bit of a wiki as an example of what I think would be helpful and then I'll do a pull request. For now I'll close out this issue though. Thank you for the help.
