### ISSUE TITLE
IDockerClient interface does not define all operation types

### ISSUE THREAD

**Issue by aemery** [Microsoft/Docker.DotNet#246]
**What version of Docker.DotNet?:**
Built three days ago following commit  eb030c0.

The IDockerClient interface does not define a few of the operation interfaces that DockerClient uses. The one that raised the issue for me is ITasksOperations, but a few more are not defined in there.

**Comment by jterry75** [comment]
I dont think I was even aware of this interface... I will get it updated but just out of curiosity, why are you using it over `DockerClient`?

**Comment by aemery** [comment]
I want to mock the client for test purposes. It will be easier to replace the client if I use the interface in the higher level classes.
