### ISSUE TITLE
[Question]Specifying filters for ContainerEventParameters

### ISSUE THREAD

**Issue by rvarna** [Microsoft/Docker.DotNet#250]
I am having trouble understanding the type of the Filters in ContainerEventParameters. Docker API specifies it  a json encoded value of the filters (a map[string][]string) to process on the event list. I would expect this to be Dictionary<string, string[]> or Dictionary<string, IList>. But why is it Dictionary<string, Dictionary<string,bool>>. What's the bool there for? Is there an example of specifying a filter that I can use?

**Comment by rvarna** [comment]
Looks like I can make the following work (but I still don't get the need for 'true'):
`
var parameters = new ContainerEventsParameters()
            {
                Filters = new Dictionary<string, IDictionary<string, bool>>()
                {
                    {
                        "event", new Dictionary<string, bool>()
                        {
                            {
                                "stop", true
                            }
                        }
                    }
                }
            };
`

**Comment by jterry75** [comment]
@rvarna - *Don't ask me* 👍 ! I think the intent of Docker here was to have the ability to whitelist/blacklist any given filter but only whitelisting works in the engine. So `"stop", true` means and apply the stop filter. I assume they wanted to also be able to support `"stop", false` which would have mean't *not applying the stop filter by default*

**Comment by rvarna** [comment]
Thanks, I am closing the issue.
