### ISSUE TITLE
Memory / CPU Limits per Container

### ISSUE THREAD

**Issue by shairozan** [Microsoft/Docker.DotNet#251]
This might be a stupid question, but now that I've got the project running and connected to my instance, I'm trying to figure out how to enforce memory / cpu slice limitations on containers at [runtime](https://docs.docker.com/engine/admin/resource_constraints/#limit-a-containers-access-to-memory).

I can see the references for Memory in the generated models, but I don't see anywhere to set that during starting, defining or start/exec of a container. Am I just missing something small?

**Comment by shairozan** [comment]
Well I think I've figured it out. Just verifying. Looks like it's part of the HostConfig subclass.

**Comment by shairozan** [comment]
Yup. Got it. It's measured in bytes. Sorry for the confusion.

**Comment by sagilevy** [comment]
If it is measured in bytes, and this property is type Int64, so the upper limit for the memory is ~2Gb?
Is there any way to increase this limit?
