### ISSUE TITLE
PushImageAsync() fails due to JSON deserialisation error

### ISSUE THREAD

**Issue by Sumo-MBryant** [Microsoft/Docker.DotNet#252]
On Docker.DotNet 3.135.0, when pushing to Amazon ECR, the `IImageOperations.PushImageAsync()` operation fails due to a JSON deserialisation error for the `Aux` property on the `JSONMessage` class.

The exception is:

```
Newtonsoft.Json.JsonSerializationException: 'Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.Collections.Generic.IList`1[System.Byte]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.
To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.
Path 'aux.Tag', line 1, position 34.'
```

A sample response that triggers this issue is:

```
{"progressDetail":{},"aux":{"Tag":"test","Digest":"sha256:632b303bfca97e96eff8ee1a7c91191778a61fc3aecc5285c6e89d0ffe130000","Size":2814}}
```

**Comment by jterry75** [comment]
Interesting. The issue is that in go `*json.RawMessage` is actually a `[]byte` type. So in C# we translate that to the `IList<byte>` in **specgen.go**. The documentation of `JSONMessage.Aux` indicates that its a dynamic object. As I see it there are two options:
1. Skip `Aux` in the output (do you need it?)
2. See if `IDictionary<string, object>` will give you the key value pairs but you will have to do all of the object value reflection yourself.

Ideas?

**Comment by Sumo-MBryant** [comment]
I personally don't need `Aux` so we could remove it and replace it with:

```csharp
[JsonExtensionData]
public IDictionary<string, object> ExtensionData { get; set; }
```

That way we don't lose information and don't make assumptions on the type of `Aux`?

**Comment by SedarG** [comment]
Hi, 
I'm hitting this issue with 3.125. Is there a workaround that I can apply? When will the fix be released?

**Comment by galvesribeiro** [comment]
@SedarG  it is probably because the 3.125 release is in fact a previous assembly. Somehow the build system got messed. Hang tight we will get a new release.

**Comment by SedarG** [comment]
Thanks!

**Comment by jterry75** [comment]
Tracking: #282
