### ISSUE TITLE
Swarm Configs support (API 1.30+)

### ISSUE THREAD

**Issue by mot256** [microsoft/Docker.DotNet#262]
We need access to the [Swarm Configs](https://docs.docker.com/engine/api/v1.31/#tag/Config) calls on the Docker Remote API. As far as we can tell, the API supports those calls from version 1.30

Are there any plans to support API 1.30+ any time soon?

**Comment by jterry75** [comment]
I am actively working on this. POR is that I am 1 by 1 going to make the set of commits from v1.25 where we are now to v1.33 where Docker is. This will include the models and api changes where applicable.

**Comment by m-barthelemy** [comment]
Hi,
Is this still something that's going to be implemented at some point?

**Comment by Crozin** [comment]
Any chance to update the lib to reflect changes made in newer API versions (current: 1.39). Mostly `Swarm.Configs` and `/update` actions for existing resources.

**Comment by Crozin** [comment]
If we could at least update the autogenerated models then I could prepare PR with required changes.

**Comment by jterry75** [comment]
Docker pretty fundamentally changed the config model. At this point I think it would actually be easier to just change the models from autogen to static. And then make the updates based on the swagger.yaml. @galvesribeiro - Should we just remove specgen and we can just update the models for each release of the Docker Remote API? I could do this work pretty easily I think.

**Comment by jterry75** [comment]
Sorry that was unclear what I said. I mean Docker changed how the vendor model of their configs works for Docker EE/CE so it makes it hard to autogen

**Comment by m-barthelemy** [comment]
Hi, any progress around stopping using autogenerated models? Or about implementing Swarm Configs?

On my end I tried to help and implement a minor feature quite some time ago but gave up when I saw this autogenerated models thing that I didn't know how to use/update.

**Comment by jterry75** [comment]
#432. This is now v1.41
