### ISSUE TITLE
Specifying ExposedPorts in createContainerAsync 

### ISSUE THREAD

**Issue by 606simps** [Microsoft/Docker.DotNet#263]
**Output of `dotnet --info`:**

```
.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
```

**What version of Docker.DotNet?:**

```
3.125.0
```

**Steps to reproduce the issue:**
1. Call createContainersAsync.

**What actually happened?:**
Don't know how to specify ExposedPorts in format of IDictionary<string, EmptyStruct>
For example: **docker run \<something\> --public 443:443 \<something\>**
I read #134, but ExposedPorts had different type IDictionary<string, object> at that time.

**What did you expect to happen?:**
0:0:0:0:443->443/tcp.

**Additional information:**

**Comment by jterry75** [comment]
Yea Docker really made this part of the API confusing. They made it a map where they actually only needed an array.

I think what you want is:
```json
ExposedPorts: {
   "443/tcp": {}//,
   // etc.
}
```

Note: This is not the same a `port mappings`. The `ExposedPorts` are used in the `--expose` portion of the cli.

So effectively in the C#
```C#
ExposedPorts = new Dictionary<string, EmptyStruct>();
ExposedPorts.Add("443/tcp", default(EmptyStruct));
```

**Comment by 606simps** [comment]
Thanks!
I figured what I really need is the port mappings(PortBinding in HostConfig).
It's working now.
