### ISSUE TITLE
new version of api in nuget

### ISSUE THREAD

**Issue by DemiusAcademius** [Microsoft/Docker.DotNet#276]
I apologize for the inappropriate question
whether this library is alive?
when a new version for nuget is expected?
Thanks!

**Comment by jterry75** [comment]
Tracking: #282

**Comment by jterry75** [comment]
This has now been published. If its not yet visible give it a few minutes as NuGet might still be indexing.

**Comment by DemiusAcademius** [comment]
Thanks!
