### ISSUE TITLE
AuthenticationException: The remote certificate is invalid according to the validation procedure.

### ISSUE THREAD

**Issue by Haxy89** [Microsoft/Docker.DotNet#278]
```
public async Task<IList<ContainerListResponse>> GetContainers()
        {
            ServicePointManager.ServerCertificateValidationCallback += (o, c, ch, er) => true;
            var credentials = new CertificateCredentials(new X509Certificate2(@"D:\Data\key.pfx", "123456"));
            ServicePointManager.ServerCertificateValidationCallback += (o, c, ch, er) => true;
            var client = new DockerClientConfiguration(new System.Uri("https://192.168.0.5:2376"), credentials).CreateClient();
            IList<ContainerListResponse> containers = await client.Containers.ListContainersAsync(new ContainersListParameters()
            {
                Limit = 10,
            });

            return containers;
        }
```

**Comment by jterry75** [comment]
How did you tie the remote pem file to this pfx?

**Comment by Haxy89** [comment]
openssl pkcs12 -export -inkey key.pem -in cert.pem -out key.pfx

I downloaded openssl.exe and run this command from docs

**Comment by jterry75** [comment]
And you run the daemon with the private pem right?

**Comment by galvesribeiro** [comment]
Are you sure the IP/host and the common names of the certificate are correct, right?

**Comment by Haxy89** [comment]
Yes, i tested IP/host and cert files with postman

**Comment by Haxy89** [comment]
@jterry75 
Yes, my daemon uses tls with key.pem and cert.pem

**Comment by Haxy89** [comment]
@galvesribeiro

Yes, thats correct.

**Comment by Haxy89** [comment]
Any clues?

**Comment by mot256** [comment]
Think you must specify the CA cert with -certfile flag when generating the PFX.

openssl pkcs12 -export -inkey key.pem -in cert.pem -out key.pfx -certfile ca.pem

This should then generate a full chain cert.

**Comment by Haxy89** [comment]
Thanks for helping. There is a bug in documentation, should be like this:
`var credentials = new CertificateCredentials(new X509Certificate2(@"D:\Download\key.pfx", "123456"));
            credentials.ServerCertificateValidationCallback += (o, c, ch, er) => true;`

**Comment by galvesribeiro** [comment]
Sorry I was out... 

@Haxy89 can you explain what the bug is?

> credentials.ServerCertificateValidationCallback += (o, c, ch, er) => true;

You know that this piece of code is supposed to only be used for simple dev/test purposes right? You should implement the logic to validate the certificate at that callback. Otherwise, you could suffer a certificate injection attack pretty easily as you are not validating the certificate and that means having the TLS enabled on the engine means nothing :)

**Comment by Haxy89** [comment]
@galvesribeiro 
My Docker uses self signed cert file so I had to use this callback. 
I am not going to release to prod env., only for dev/test purposes, I am playing with webapi and angular :)

The documentation says to use callback like this: ` ServicePointManager.ServerCertificateValidationCallback += (o, c, ch, er) => true;` but this have not worked for me.

Correct use is: `credentials.ServerCertificateValidationCallback += (o, c, ch, er) => true;` as a method for CertificateCredentials object class.

**Comment by jterry75** [comment]
What .net version were you targeting? Looking at the code the only time that we don't fetch the global's if you didn't set the instance value is in `.netstandard1.6`. So I can update the docs to say you need to set the instance in `.netstandard1.6` but just wanted to make sure that's what you were using.

**Comment by Haxy89** [comment]
@jterry75 
I am using dotnetcore2.0

**Comment by jterry75** [comment]
Well I don't understand how setting the global in your case did not solve the issue. But I will update the documentation to describe setting it on the local object too.

**Comment by Haxy89** [comment]
Thanks :)
