### ISSUE TITLE
Nuget package 3.125 has the previous DLL version inside

### ISSUE THREAD

**Issue by nvivo** [Microsoft/Docker.DotNet#279]
I was looking for the Prune apis and couldn't find, even though it should be there.
So I found that the current `3.125` package published has the `2.124` dll version inside.

![image](https://user-images.githubusercontent.com/202449/35471935-932e00be-034c-11e8-952f-dd1f70fa94f1.png)

![image](https://user-images.githubusercontent.com/202449/35471925-5d899a0e-034c-11e8-840e-d7eb04cb9923.png)

This is the [official nuget package](https://www.nuget.org/packages/Docker.DotNet/3.125.0) as of this post.

**Comment by nvivo** [comment]
cc @jterry75

**Comment by nvivo** [comment]
@galvesribeiro Just trying to get attention of any contributors to this. I think nobody is looking at these issues.

**Comment by galvesribeiro** [comment]
Hello, 

We are looking at the issues.

I indeed got the same file version here:

![image](https://user-images.githubusercontent.com/4714040/35584278-aa5873be-05db-11e8-863b-78d89260402d.png)

Do we have any problems with the CI @jterry75 ?

**Comment by jterry75** [comment]
I think we need to just tag another release and push it. I dont quite understand how it got mixed up. I will try and do that today. Given that there is no new work for any newer API's i think we want to call it `3.125.1` does that sound good?

**Comment by galvesribeiro** [comment]
@jterry75 there are issues. Lets first see if there is something that requires a PR.

**Comment by jterry75** [comment]
Tracking: #282.

**Comment by jterry75** [comment]
This has now been published. If its not yet visible give it a few minutes as NuGet might still be indexing.
