### ISSUE TITLE
Wrong Http Request Version

### ISSUE THREAD

**Issue by jamiewest** [Microsoft/Docker.DotNet#285]
**Output of `dotnet --info`:**

```
.NET Command Line Tools (2.1.4)

Product Information:
 Version:            2.1.4
 Commit SHA-1 hash:  5e8add2190

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.4\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54
```

**What version of Docker.DotNet?:**

```
3.125.1
```

**Steps to reproduce the issue:**
1. Spin up a new Xamarin.Forms project in VS2017, (UWP, Andriod, iOS along with netstandard).
2. Add Docker.DotNet to project and try to connect using a certificate.
3. This message shows up: System.AggregateException: 'One or more errors occurred. (Docker API responded with status code=BadRequest, response=400 Bad Request: unsupported protocol version)'

**What actually happened?:**
When the ManagedHandler creates a new HttpRequestMessage, the default Http request version is 2.0 and then docker throws a fit.

**What did you expect to happen?:**
The default version should be 1.1

**Additional information:**
When using this library on a .NET Core Console app, the Http request version is 1.1. Most likely this issue is related to the underlying framework's (Mono / .NET Core) implementation. Just wanted to have an issue out there for others hitting this.

**Comment by jterry75** [comment]
This was fixed.
