### ISSUE TITLE
Connecting to Docker on an Azure VM on a VNET fails when trying to connect to a private IP address 

### ISSUE THREAD

**Issue by jon-swain-autocab** [Microsoft/Docker.DotNet#311]
**What version of Docker.DotNet?:**

3.125.2

**Steps to reproduce the issue:**

1. Setup two VMs on Azure running docker for windows connected via a Virtual Network
2. On the first VM run a console app (See source below) which tries to connect to docker on the second VM using the PRIVATE IP and list the containers. 

NOTE. The PRIVATE IP addresses i used were 10.0.1.4 and 10.0.2.4

**What actually happened?:**

The console app fails to connect with the the exception "An attempt was made to access a socket in a way forbidden by its access permissions".

**What did you expect to happen?:**

A successful connection which lists the containers.

**Additional information:**

Having investigated this issue for a while i discovered the following solution

By changing the following code in ManagedHandler.TCPSocketOpenerAsync i have fixed the problem.

Change the line (332) 

`var s = new Socket(SocketType.Stream, ProtocolType.Tcp);`

To 

`var s = new Socket(address.AddressFamily, SocketType.Stream, ProtocolType.Tcp);`

**Console App Example**

	static async Task Main( string[] args )
	{
		string privateIP = "10.0.1.4";
		int port = 2375;

		Console.WriteLine( $"Attempting connection to @ PRIVATE IP {privateIP} on port {port}" );

		try
		{
			using( var docker = new DockerClientConfiguration( new Uri( $"http://{privateIP}:{port}" ) ).CreateClient() )
			{
				var containers = await docker.Containers.ListContainersAsync( new ContainersListParameters
				{
					All = true
				} );

				foreach( var container in containers )
				{
					var name = container.Names.Single().Substring( 1 );

					Console.WriteLine( $"Found Container {name}" );
				}
			}

			Console.WriteLine( $"Successfully connected to @ PRIVATE IP {privateIP} on port {port}" );
		}
		catch( Exception ex )
		{
			Console.WriteLine( $"Failed to connect to @ PRIVATE IP {privateIP} on port {port} - {ex}" );
			Console.WriteLine( $"StackTrace - {ex.Message}" );
		}
	}

**Comment by jterry75** [comment]
Seems like an oversight to not pass the `AddressFamily` and use a smaller constructor for the `Socket` class. Want to PR this change up or would you like me to do it?
