### ISSUE TITLE
PruneChildren actually means no prune children...

### ISSUE THREAD

**Issue by JasonStein** [Microsoft/Docker.DotNet#315]
Hey, just noticed that PruneChildren = true (ImageDeleteParameters) actually means no prune children according to Docker API and my observation (did an integration test to verify my guess), should we consider to name it NoPruneChildren instead? Or flip the Boolean value before sending out the request to docker daemon? Since PruneChildren is called "--no-prune" in Docker API.

**Comment by jterry75** [comment]
I have no idea why this would of been implemented this way. You are 100% correct. We should change the model to NoPrune and update the ImageDeleteParameters. Do you want to PR up this change?

**Comment by JasonStein** [comment]
Sure, I will send out a PR and post link here. Thanks for the quick response!

**Comment by JasonStein** [comment]
Here is the PR: https://github.com/Microsoft/Docker.DotNet/pull/316
Let me know if this change is sufficient or tests need to be fixed or added.

**Comment by JasonStein** [comment]
PR get merged, feel free to close this issue:) @jterry75

**Comment by jterry75** [comment]
Thanks again @JasonStein
