### ISSUE TITLE
Codegen tool and query parameters for TasksOperations.ListAsync

### ISSUE THREAD

**Issue by andrey-skat** [Microsoft/Docker.DotNet#318]
Task listing method doesn't have parameter for filtering. As I understand before add it, I should run codegen tool to generate new models. I tried to run it, but got errors.
```
.\specgen.go:99:27: undefined: types.ContainerChange
.\specgen.go:113:27: undefined: types.ContainerProcessList
.\specgen.go:115:27: undefined: types.ImageDelete
.\specgen.go:116:27: undefined: types.ImageHistory
.\specgen.go:194:17: undefined: types.ContainerChange
.\specgen.go:239:17: undefined: types.ContainerProcessList
.\specgen.go:285:17: undefined: types.ImageDelete
.\specgen.go:288:17: undefined: types.ImageHistory
```

Is codegen tool still working?

**Comment by jterry75** [comment]
Yes codegen works for me. Did you restore the vendor files? What is the specific method you are trying to add filtering for?

**Comment by andrey-skat** [comment]
I tried to add filtering for `TasksOperations.ListAsync`. I found that it has `filters` [parameter](https://github.com/moby/moby/blob/5e11f66cb6de472d11647e8b1a744afc941859ad/api/types/client.go#L350), but it doesn't exist in the dotnet client.

**Comment by jterry75** [comment]
Oh I see. There is no parameters at all for ListAsync. I will submit a fix for this for ya. Thanks for pointing it out.
