### ISSUE TITLE
[Question] - run a command in a container

### ISSUE THREAD

**Issue by dazinator** [Microsoft/Docker.DotNet#325]
I was wondering if it was currently possible to execute a command inside a running container, and retrieve its stdout. I'd like to use `Docker.DotNet` to start a build container, and then execute a shell command inside that does the build within the container, and basically pipe out the STDOUT so I can work out the results!

**Comment by jterry75** [comment]
There are a couple of ways to accomplish this. Basically your container process (the init process) needs to stay alive to keep the container running. Lets call this a sleep process `s` that is really just any long running process. Then you can `exec` `N` number of processes in the lifetime of `s`.

So via `Docker` this would look something like:
```bash
docker run busybox sh -c "sleep 5m"
```
In a different shell:
```bash
docker exec <id> sh -c "ps -a"
```

And in `Docker.DotNet` the same API's are available at a programmable layer. Create/Start/Exec.

Hope this help.

**Comment by dazinator** [comment]
Excellent. Thank you.
