### ISSUE TITLE
Connet set CreateContainerParameters Hostname

### ISSUE THREAD

**Issue by dave4you** [Microsoft/Docker.DotNet#326]
**Output of `dotnet --info`:**

```
.NET Command Line Tools (2.1.104)

Product Information:
 Version:            2.1.104
 Commit SHA-1 hash:  48ec687460

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.104\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.6
  Build    : 74b1c703813c8910df5b96f304b0f2b78cdf194d
```

**What version of Docker.DotNet?:**

```
3.125.2

```

**Steps to reproduce the issue:**
Create container using CreateContainerParameters.Hostname  
e.g: .Hostname = "MyName"

**What actually happened?:**
The created container got a replacement name like xenodochial_aryabhata, gifted_goldberg etc. 
Just like one would receive when one would not provide a name for a new container.

**What did you expect to happen?:**
To have a container created with the given name using CreateContainerParameters. 
e.g: .Hostname = "MyName"

**Additional information:**

Setting hostname while creating container.
Investigating the matter, I found that the CreateContainerAsync(ContainerParameters.hostname generates "Hostname":"myname"
While a retrieved object using Containers.ListContainersAsync gives me 
"Names":["myname"]

**Comment by jterry75** [comment]
These are not the same things I don't think. I believe `.HostName` correlates to the name the container sees itself as; ie: For name resolution purposes. What you want is to set `.Name` in the create parameters. This gets passed as the query string which Docker uses to allocate the `Name` of the container

**Comment by dave4you** [comment]
Great. Thanks for the explanation!
