### ISSUE TITLE
Support for container update?

### ISSUE THREAD

**Issue by jonso4** [Microsoft/Docker.DotNet#327]
There has been a todo in ContainerOperations.cs for a while to support container update. Is there an ETA on this?

**Comment by jterry75** [comment]
@jonso4 - ATM I don't have time to contribute this. Would you be willing to take a crack at it?

**Comment by jonso4** [comment]
Sure!

**Comment by jonso4** [comment]
Just sent a PR: https://github.com/Microsoft/Docker.DotNet/pull/328

**Comment by jterry75** [comment]
Again thanks!

**Comment by jonso4** [comment]
Great! Is there an ETA for the next release with this patch?

**Comment by jterry75** [comment]
Will try to get these changes out later today

**Comment by jonso4** [comment]
@jterry75 any update on this?

**Comment by jterry75** [comment]
Sorry I was waiting for confirmation of: [323](https://github.com/Microsoft/Docker.DotNet/pull/323) will update without it for now.

**Comment by jterry75** [comment]
@jonso4 - I have not forgotten about this. There are some internal changes that have to be approved before I can submit this release. Will update as soon as possible

**Comment by jonso4** [comment]
@jterry75 not a problem, thanks for the update.
