### ISSUE TITLE
Exposing container ports to the outside world

### ISSUE THREAD

**Issue by SeanFarrow** [Microsoft/Docker.DotNet#337]
Hi,

How do I expose a container port to the outside world using docker.net? I'm working with a PostGres container and need to expose port 5432, Currently, I'm creating a dictionary of a string and a NoEmptyStruct and adding the port in the form $"{containerPort}:{hostPort}", but when running PostGres, the connection is being refused. I can do this using docker at the commandline quite happily, so know it's my docker.net code.
Any help appreciated.
Cheers
Sean.

**Comment by SeanFarrow** [comment]
@Justin,
Thanks, is there a way to map all exposed container ports to random ports on the host to simulate the -P docker run command line parameter?
Such as:
docker run --name mynginx1 -P -d nginx

**Comment by jterry75** [comment]
Yes set
```C#
new HostConfig
{
    // ...
    PublishAllPorts = true,
    // ...
}
```

**Comment by SeanFarrow** [comment]
Thanks, that worked, so feel free to close.
