### ISSUE TITLE
Question about progress updates when working with images 

### ISSUE THREAD

**Issue by spoon252** [Microsoft/Docker.DotNet#339]
Hello, this is the first time I'm posting here so maybe it's incorrect way but i'm asking for a couple of hints as I recently started using docker.dotnet to implement some automatic manipulation of images and containers program.
I have implemented a pull function that downloads from azure container registry. it works fine, and images are downloaded, but the problem is with progress as it floods my console window. I think on every progress update i get another output instead of having a progress structure that docker gives when run from cmd or ps.

this is the code, where on ProgressOutput i just wrote a method that writes some parts of this JSONMessage object (status, error and such)...

try
            {
                var progress = new Progress<JSONMessage>(msg =>
                {
                    ProgressOutput.WriteProgress(msg);
                });

                AuthConfig authConfig = new AuthConfig()
                {
                    ServerAddress = ConfigurationManager.AppSettings["AcrLoginServer"],
                    Password = ConfigurationManager.AppSettings["AcrPassword"],
                    Username = ConfigurationManager.AppSettings["AcrLoginName"],
                };
                await client.Images.CreateImageAsync(
                new ImagesCreateParameters()
                {
                    FromImage = webjobimage.image_name +":"+ webjobimage.image_version,
                },
                authConfig,
                progress
                );
                imageList = ListLocal().Result;
               

            }
            catch (Exception ex)
            {
                Console.WriteLine($"Exception thrown attempting to pull image to {client.Configuration.EndpointBaseUri}");
                Console.WriteLine($"{ex}");
            }

I'm interested if there is some way to kind of filter this progress output so i get something like this https://files.readme.io/c212fce-skil_docker_pull_image.png
im fairly new to this whole thing, both c# and docker

thanks :D

**Comment by jterry75** [comment]
The `JSONMessage` that is returned on each update from the daemon should contain a `.Progress` property. This is a `JSONProgress` message from the daemon that should contain `.Current ; .Total ; .Start` properties. In order to implement something like that you have to take the `Total / (Space you have in your UI)` to build chunks on the Progress bar `0 -> 100%` in `1%` increments lets say. And then place `.Current` in one of those increments. Does that make sense?

**Comment by spoon252** [comment]
thanks for your response
Yes I had very similar idea to that one when i noticed JSONProgress.Progress and that it has current total and start properties. I think for my solution it's enough to just write percentages on their own so they can be incrementing to 100% in one line rather than being written down on every progress update.
Just that i'm not sure of implementation.
My method for writing output looks like this

class ProgressOutput
    {
        public static void WriteProgress(JSONMessage prog_msg)
        {
            Console.WriteLine($"{prog_msg.Status}|{prog_msg.ProgressMessage}|{prog_msg.ErrorMessage}");
        }
}

very trivial i think. So I should add the incrementations here somehow. Numbers being written out is enough for me, just so that a single layer downloading takes only one line.

**Comment by jterry75** [comment]
Ah. Take a look at a Console Cursor. You can set the position to where you want and then draw the text on each iteration to show the updates. In PowerShell they have this built in with tasks but I don't think CMD does by default.
