### ISSUE TITLE
Adding -i kind of flag when specifying ContainerCreateParameters

### ISSUE THREAD

**Issue by spoon252** [Microsoft/Docker.DotNet#341]
This is more of a question but how can i add the flag for interactive mode when creating a container.
My CreateContainerParameters looks like following:

CreateContainerResponse response = await client.Containers.CreateContainerAsync(new CreateContainerParameters
                {
                    Image = container.ImageID,                    
                    HostConfig = new HostConfig
                    {
                        NetworkMode = "host"
                    },             
                });

and after that i attach and start container with

await client.Containers.AttachContainerAsync(container.ContainerID, true,  new ContainerAttachParameters
                {
                    Stdin = true,
                    Stderr = true,
                    Stdout = true
                });

but containers that require -i when being run from cmd are exited instantly after they are started. Any idea how to implement -i in create function?

**Comment by jterry75** [comment]
Closing same as #224
