### ISSUE TITLE
GetContainerLogs preprends junk characters to log lines

### ISSUE THREAD

**Issue by Davipb** [microsoft/Docker.DotNet#359]
**Output of `dotnet --info`:**

```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.500
 Commit:    b68b931422

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.500\

Host (useful for support):
  Version: 2.1.6
  Commit:  3f4f8eebd8

.NET Core SDKs installed:
  2.1.104 [C:\Program Files\dotnet\sdk]
  2.1.200 [C:\Program Files\dotnet\sdk]
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.302 [C:\Program Files\dotnet\sdk]
  2.1.400 [C:\Program Files\dotnet\sdk]
  2.1.401 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]
  2.1.403 [C:\Program Files\dotnet\sdk]
  2.1.500 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.3-servicing-26724-03 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**What version of Docker.DotNet?:**
3.125.2

**Steps to reproduce the issue:**
1. `git clone git@github.com:Davipb/Docker.DotNet.LogsIssue.git`
2. `cd Docker.DotNet.LogsIssue`
3. `dotnet run`

Or, to do it manually:

1. `docker run hello-world`
2. Get the container ID with `docker container ls -a --filter ancestor=hello-world --format "{{.ID}}"`
3. Call `DockerClient.Containers.GetContainerLogsAsync` with the ID you found
4. Inspect the strings returned to the `IProgress`

**What actually happened?:**
The returned log lines have junk characters prepended to them. 
This happens because Docker sends a string length prefix when returning the logs, and the library
interprets them as characters part of the logs themselves.

**What did you expect to happen?:**
The logs should be returned cleanly, as the container printed them.

**Additional information:**
The cause of this issue becomes more obvious if we use the now-obsolete version of `GetContainerLogsAsync` that returns a `Stream`.
The stream first sends 8 bytes containing a big-endian 64-bit integer indicating the length of the string to come, and then that exact amount of bytes representing a UTF-8 string.
It seems that the library simply interprets the whole thing as one big string, and so those length prefixes become junk characters.

**Comment by jterry75** [comment]
Well I see a couple of bugs here.

Unfortunately it looks like the https://docs.docker.com/engine/api/v1.26/#operation/ContainerLogs endpoint returns differently based on two scenarios that we aren't handling.

If `parameters.Follow == true` we need to be using the `MakeRequestForHijackedStreamAsync` request/response mechanism. And in either case if the container is using TTY we read the stream directly otherwise we need to use the `MultiplexedStream` to handle the `stdin/stdout` in the same stream. 

Here is a good description of the problem and how the docker client handles it: https://github.com/moby/moby/blob/master/client/container_logs.go#L14

We have everything we need here in place already but just need to stitch it all together to handle the new scenarios that were added.

**Comment by jhastings88** [comment]
Whats the status of this bug fix?

**Comment by adragoset** [comment]
Interested in this fix as I am getting both garbage characters in log output but additionally following a stream is not working correctly.
