### ISSUE TITLE
Update Docker API

### ISSUE THREAD

**Issue by dorny** [microsoft/Docker.DotNet#381]
This library supports Docker API of version 1.25.
This wasn't updated in more than 2 years.
Is there anything preventing updating of models to match more recent API versions?

I'm missing possibility to create a swarm service with a read-only option. This is available since version 1.26.

Related #172

**Comment by thomasf1234** [comment]
Also requiring the GET /service/{id}/logs endpoint from 1.26

**Comment by jterry75** [comment]
#432. This is now v1.41
