### ISSUE TITLE
API calls are failing with "Operation timedout" when the APIs are invoked from container

### ISSUE THREAD

**Issue by ganga1980** [Microsoft/Docker.DotNet#382]
**Output of `dotnet --info`:**

```
(paste your output here)
```

**What version of Docker.DotNet?:**
3.125.2.0
```
(paste your output here)
```
The operation has timed out

**Steps to reproduce the issue:**
1. Build the simple windows .net (core or framework) test container which uses Docker.Dotnet
2.  run the container with 
docker run -it -u ContainerAdministrator ganga1980/docker-namedpipe-test-df:03292019-1 -v \\.\pipe\docker_engine:\\.\pipe\docker_engine -- cmd

3.  all the API calls are failing with operation timedout and same code works in non-containerized app.

**What actually happened?:**
API calls are failing Operation timedout

**What did you expect to happen?:**
API calls should be successful

**Additional information:**
Here is the snippet of the code

   DockerClient client =
                        new DockerClientConfiguration(new Uri("npipe://./pipe/docker_engine")).CreateClient();

                    Console.WriteLine("after the client object construction ");

                    var config = client.Configuration;

                    Console.WriteLine("before calling list containers");

                    var containers = client.Containers.ListContainersAsync(
                    new ContainersListParameters()
                    {
                        Limit = 1,
                    }).GetAwaiter().GetResult();

                    foreach (var container in containers)
                    {
                        Console.WriteLine("Container Id : {0}, ImageId: {1}, Image: {2}", container.ID, container.ImageID, container.Image);
                    }

**Comment by YavorYanchev** [comment]
I have the the same issue. The calls are working locally,but when I use them in container  I get timeout .
I am using named pipes and I am running the container with
 `-v \\.\pipe\docker_engine:\\.\pipe\docker_engine`
I really need to make this work.  @jterry75 Can you help us?
I will be really glad if someone can point me in the right direction. :)

**Comment by ganga1980** [comment]
@YavorYanchev, There is no issue Docker.Dotnet Library. Issue with the format of the mount.
 Here is the docker run command which I used and working one

docker run -it -v //./pipe/docker_engine://./pipe/docker_engine<image> -u ContainerAdministrator – cmd

**Comment by YavorYanchev** [comment]
Hi @ganga1980 ! I tried with your command, but I still get timout. Do you have something special in your Dockerfile?

I am probably missing something small :/

My app is: 
`static void Main(string[] args)
        {
            try
            {
                var clientConfiguration = new DockerClientConfiguration(new Uri("npipe://./pipe/docker_engine"));
                var client = clientConfiguration.CreateClient();

                Console.WriteLine("-------------->>>Successful creation of client!");
                
                var images = client.Containers.ListContainersAsync(new ContainersListParameters { Limit = 1}).GetAwaiter().GetResult();
                foreach (var image in images)
                {
                    Console.WriteLine(image.ID);
                }
            }
            catch (Exception e)
            {
                Console.WriteLine("(>)(>)(>)(>)=>" + e.HResult);
                Console.WriteLine(e);
            }

            while (true)
            {
                Thread.Sleep(3000);
            }
        }`

**Comment by eriksundberg-tui** [comment]
Hi,

Had this issue and I think it was because the container is running linux, meaning 
 "pipe://./pipe/docker_engine" doesn't connect to anything.

Instead I solved it by:
`
            var uri = new Uri("npipe://./pipe/docker_engine");
            if (RuntimeInformation.IsOSPlatform(OSPlatform.Linux))
                uri = new Uri("unix:///var/run/docker.sock");

            var dockerClient = new DockerClientConfiguration(uri).CreateClient();
`

And then when starting the container with:
`docker run -it -v /var/run/docker.sock:/var/run/docker.sock <containerName>`

**Comment by xammob** [comment]
I've got exactly this issue but for me it's only a problem when using .net framework. A little console app created with .net core works fine. I'm using windows based containers and I've tried both combinations of -v \\.\pipe\docker_engine:\\.\pipe\docker_engine and -v //./pipe/docker_engine://./pipe/docker_engine. Works fine in .net core, times out in .net framework
