### ISSUE TITLE
How can I get progress in realtime from BuildImageFromDockerfileAsync?

### ISSUE THREAD

**Issue by MorenoGentili** [microsoft/Docker.DotNet#423]
Hi, I'd like to report progress in realtime when I invoke `BuildImageFromDockerfileAsync` since this is an operation that could take several seconds or even minutes, depending on the Dockerfile.

At the moment, the `BuildImageFromDockerfileAsync` method returns a `Task<Stream>` [as you can see here](https://github.com/microsoft/Docker.DotNet/blob/40f19a2fe1a3ad0d4bb3269b969a35ca952df39e/src/Docker.DotNet/Endpoints/ImageOperations.cs#L46) and that allows me to get the full command output but only when the operation has ended. Instead, I want to be able to get the progress in realtime, as soon as it's outputted by Docker.

Thanks

**Comment by shargon** [comment]
If you read line by line, you can do that

**Comment by MorenoGentili** [comment]
Silly me, I didn't realize the `BuildImageFromDockerfileAsync` method returned a `Stream` right away. For some reason I thought it would wait until the build ended. Reading line by line works.
```
using var responseStream = await docker.Images.BuildImageFromDockerfileAsync(result.Tarball, imageBuildParameters);
using var streamReader = new StreamReader(responseStream);

while (!streamReader.EndOfStream)
{
  string? outputLine = await streamReader.ReadLineAsync();
  if (!string.IsNullOrEmpty(outputLine))
  {
     //Do something with the line (e.g. notify client via SignalR)
  }
}
```
Thank you very much!
